In [1]:
from __future__ import division
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from scipy.spatial.distance import cosine
from scipy.sparse import csr_matrix

In [2]:
pd.set_option('display.float_format', lambda x: '%.3f' %x)

In [3]:
with open('HAPT Data Set/features.txt') as handle:
    features = handle.readlines()
    features = map(lambda x: x.strip(), features)

In [4]:
with open('HAPT Data Set/activity_labels.txt') as handle:
    activity_labels = handle.readlines()
    activity_labels = map(lambda x: x.strip(), activity_labels)

In [5]:
activity_dataset = pd.DataFrame(list(activity_labels))
activity_dataset = pd.DataFrame(activity_dataset[0].str.split(' ').tolist(), 
                                columns = ['activity_id', 'activity_label'])

In [6]:
x_train = pd.read_table('HAPT Data Set\Train\X_train.txt', header = None, sep = " ", names = list(features))
x_train.iloc[:10, :10].head()
x_train.shape

C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\site-packages\pandas\io\parsers.py:678: UserWarning: Duplicate names specified. This will raise an error in the future.
  return _read(filepath_or_buffer, kwds)


(7767, 561)

In [7]:
x_test = pd.read_table('HAPT Data Set/Test/X_test.txt', header = None, sep = " ")
x_test.shape

(3162, 561)

In [8]:
y_train = pd.read_table('HAPT Data Set\Train\y_train.txt', header = None, sep = ' ', names = ['activity_id'])
y_train.head()

activity_id
0            5
1            5
2            5
3            5
4            5

In [9]:
# Fitting Random Forest Classification to the Training set
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 0)
classifier.fit(x_train, y_train)

C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\site-packages\ipykernel_launcher.py:4: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  after removing the cwd from sys.path.


RandomForestClassifier(bootstrap=True, class_weight=None, criterion='entropy',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
            oob_score=False, random_state=0, verbose=0, warm_start=False)

In [10]:
# Predicting the Test set results
y_pred = classifier.predict(x_test)

In [11]:
y_test = pd.read_table('HAPT Data Set/Test/y_test.txt', header = None, sep = " ")
y_test.shape

(3162, 1)

In [12]:
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)

In [13]:
print(cm)

[[481   5  10   0   0   0   0   0   0   0   0   0]
 [ 62 402   7   0   0   0   0   0   0   0   0   0]
 [ 23  50 347   0   0   0   0   0   0   0   0   0]
 [  0   0   0 445  60   1   2   0   0   0   0   0]
 [  0   0   0  59 492   3   2   0   0   0   0   0]
 [  1   0   0   0   0 543   0   0   0   0   1   0]
 [  0   2   0   3   0   0  17   0   0   0   1   0]
 [  0   0   0   0   0   0   0   8   0   1   1   0]
 [  0   0   0   1   0   0   0   0  21   0  10   0]
 [  0   0   0   0   0   0   1   0   0  17   0   7]
 [  2   1   0   2   0   0   3   0  13   1  27   0]
 [  0   1   0   0   0   0   1   0   1  10   1  13]]


In [14]:
classifier.score(x_test, y_test)

0.8896268184693232